export const CURRENCIES = [
  { key: 'AED', value: 'AED', label: 'AED - United Arab Emirates dirham' },
  { key: 'AFN', value: 'AFN', label: 'AFN - Afghan afghani' },
  { key: 'ALL', value: 'ALL', label: 'ALL - Albanian lek' },
  { key: 'AMD', value: 'AMD', label: 'AMD - Armenian dram' },
  { key: 'AOA', value: 'AOA', label: 'AOA - Angolan kwanza' },
  { key: 'ARS', value: 'ARS', label: 'ARS - Argentine peso' },
  { key: 'AUD', value: 'AUD', label: 'AUD - Australian dollar' },
  { key: 'AWG', value: 'AWG', label: 'AWG - Aruban florin' },
  { key: 'AZN', value: 'AZN', label: 'AZN - Azerbaijani manat' },
  { key: 'BAM', value: 'BAM', label: 'BAM - Bosnia and Herzegovina convertible mark' },
  { key: 'BBD', value: 'BBD', label: 'BBD - Barbados dollar' },
  { key: 'BDT', value: 'BDT', label: 'BDT - Bangladeshi taka' },
  { key: 'BGN', value: 'BGN', label: 'BGN - Bulgarian lev' },
  { key: 'BHD', value: 'BHD', label: 'BHD - Bahraini dinar' },
  { key: 'BIF', value: 'BIF', label: 'BIF - Burundian franc' },
  { key: 'BMD', value: 'BMD', label: 'BMD - Bermudian dollar' },
  { key: 'BND', value: 'BND', label: 'BND - Brunei dollar' },
  { key: 'BOB', value: 'BOB', label: 'BOB - Boliviano' },
  { key: 'BOV', value: 'BOV', label: 'BOV - Bolivian Mvdol (funds code)' },
  { key: 'BRL', value: 'BRL', label: 'BRL - Brazilian real' },
  { key: 'BSD', value: 'BSD', label: 'BSD - Bahamian dollar' },
  { key: 'BTN', value: 'BTN', label: 'BTN - Bhutanese ngultrum' },
  { key: 'BWP', value: 'BWP', label: 'BWP - Botswanan pula' },
  { key: 'BYN', value: 'BYN', label: 'BYN - Belarusian ruble' },
  { key: 'BZD', value: 'BZD', label: 'BZD - Belize dollar' },
  { key: 'CAD', value: 'CAD', label: 'CAD - Canadian dollar' },
  { key: 'CDF', value: 'CDF', label: 'CDF - Congolese franc' },
  { key: 'CHF', value: 'CHF', label: 'CHF - Swiss franc' },
  { key: 'CLP', value: 'CLP', label: 'CLP - Chilean peso' },
  { key: 'CNY', value: 'CNY', label: 'CNY - Chinese yuan' },
  { key: 'COP', value: 'COP', label: 'COP - Colombian peso' },
  { key: 'CRC', value: 'CRC', label: 'CRC - Costa Rican colón' },
  { key: 'CUC', value: 'CUC', label: 'CUC - Cuban convertible peso' },
  { key: 'CUP', value: 'CUP', label: 'CUP - Cuban peso' },
  { key: 'CVE', value: 'CVE', label: 'CVE - Cape Verdean escudo' },
  { key: 'CZK', value: 'CZK', label: 'CZK - Czech koruna' },
  { key: 'DJF', value: 'DJF', label: 'DJF - Djiboutian franc' },
  { key: 'DKK', value: 'DKK', label: 'DKK - Danish krone' },
  { key: 'DOP', value: 'DOP', label: 'DOP - Dominican peso' },
  { key: 'DZD', value: 'DZD', label: 'DZD - Algerian dinar' },
  { key: 'EGP', value: 'EGP', label: 'EGP - Egyptian pound' },
  { key: 'ERN', value: 'ERN', label: 'ERN - Eritrean nakfa' },
  { key: 'ESP', value: 'ESP', label: 'ESP - Spanish peseta' },
  { key: 'ETB', value: 'ETB', label: 'ETB - Ethiopian birr' },
  { key: 'EUR', value: 'EUR', label: 'EUR - Euro' },
  { key: 'FJD', value: 'FJD', label: 'FJD - Fijian dollar' },
  { key: 'FKP', value: 'FKP', label: 'FKP - Falkland Islands pound' },
  { key: 'GBP', value: 'GBP', label: 'GBP - British pound' },
  { key: 'GEL', value: 'GEL', label: 'GEL - Georgian lari' },
  { key: 'GHS', value: 'GHS', label: 'GHS - Ghanaian cedi' },
  { key: 'GIP', value: 'GIP', label: 'GIP - Gibraltar pound' },
  { key: 'GMD', value: 'GMD', label: 'GMD - Gambian dalasi' },
  { key: 'GNF', value: 'GNF', label: 'GNF - Guinean franc' },
  { key: 'GQE', value: 'GQE', label: 'GQE - Equatorial Guinean ekwele' },
  { key: 'GRD', value: 'GRD', label: 'GRD - Greek drachma' },
  { key: 'GTQ', value: 'GTQ', label: 'GTQ - Guatemalan quetzal' },
  { key: 'GUF', value: 'GUF', label: 'GUF - French Guiana franc' },
  { key: 'GUM', value: 'GUM', label: 'GUM - Guam dollar' },
  { key: 'GUY', value: 'GUY', label: 'GUY - Guyanese dollar' },
  { key: 'HKD', value: 'HKD', label: 'HKD - Hong Kong dollar' },
  { key: 'HNL', value: 'HNL', label: 'HNL - Honduran lempira' },
  { key: 'HRK', value: 'HRK', label: 'HRK - Croatian kuna' },
  { key: 'HTG', value: 'HTG', label: 'HTG - Haitian gourde' },
  { key: 'HUF', value: 'HUF', label: 'HUF - Hungarian forint' },
  { key: 'IDR', value: 'IDR', label: 'IDR - Indonesian rupiah' },
  { key: 'ILS', value: 'ILS', label: 'ILS - Israeli new shekel' },
  { key: 'INR', value: 'INR', label: 'INR - Indian rupee' },
  { key: 'IQD', value: 'IQD', label: 'IQD - Iraqi dinar' },
  { key: 'IRR', value: 'IRR', label: 'IRR - Iranian rial' },
  { key: 'ISK', value: 'ISK', label: 'ISK - Icelandic króna' },
  { key: 'JMD', value: 'JMD', label: 'JMD - Jamaican dollar' },
  { key: 'JOD', value: 'JOD', label: 'JOD - Jordanian dinar' },
  { key: 'JPY', value: 'JPY', label: 'JPY - Japanese yen' },
  { key: 'KES', value: 'KES', label: 'KES - Kenyan shilling' },
  { key: 'KGS', value: 'KGS', label: 'KGS - Kyrgyzstani som' },
  { key: 'KHR', value: 'KHR', label: 'KHR - Cambodian riel' },
  { key: 'KMF', value: 'KMF', label: 'KMF - Comorian franc' },
  { key: 'KPW', value: 'KPW', label: 'KPW - North Korean won' },
  { key: 'KRW', value: 'KRW', label: 'KRW - South Korean won' },
  { key: 'KWD', value: 'KWD', label: 'KWD - Kuwaiti dinar' },
  { key: 'KYD', value: 'KYD', label: 'KYD - Cayman Islands dollar' },
  { key: 'KZT', value: 'KZT', label: 'KZT - Kazakhstani tenge' },
  { key: 'LAK', value: 'LAK', label: 'LAK - Laotian kip' },
  { key: 'LBP', value: 'LBP', label: 'LBP - Lebanese pound' },
  { key: 'LKR', value: 'LKR', label: 'LKR - Sri Lankan rupee' },
  { key: 'LRD', value: 'LRD', label: 'LRD - Liberian dollar' },
  { key: 'LSL', value: 'LSL', label: 'LSL - Lesotho loti' },
  { key: 'LTL', value: 'LTL', label: 'LTL - Lithuanian litas' },
  { key: 'LVL', value: 'LVL', label: 'LVL - Latvian lats' },
  { key: 'LYD', value: 'LYD', label: 'LYD - Libyan dinar' },
  { key: 'MAD', value: 'MAD', label: 'MAD - Moroccan dirham' },
  { key: 'MDL', value: 'MDL', label: 'MDL - Moldovan leu' },
  { key: 'MGA', value: 'MGA', label: 'MGA - Malagasy ariary' },
  { key: 'MKD', value: 'MKD', label: 'MKD - Macedonian denar' },
  { key: 'MMK', value: 'MMK', label: 'MMK - Myanmar kyat' },
  { key: 'MNT', value: 'MNT', label: 'MNT - Mongolian tögrög' },
  { key: 'MOP', value: 'MOP', label: 'MOP - Macanese pataca' },
  { key: 'MRU', value: 'MRU', label: 'MRU - Mauritanian ouguiya' },
  { key: 'MUR', value: 'MUR', label: 'MUR - Mauritian rupee' },
  { key: 'MVR', value: 'MVR', label: 'MVR - Maldivian rufiyaa' },
  { key: 'MWK', value: 'MWK', label: 'MWK - Malawian kwacha' },
  { key: 'MXN', value: 'MXN', label: 'MXN - Mexican peso' },
  { key: 'MXV', value: 'MXV', label: 'MXV - Mexican Investment Unit (UDI)' },
  { key: 'MYR', value: 'MYR', label: 'MYR - Malaysian ringgit' },
  { key: 'MZN', value: 'MZN', label: 'MZN - Mozambican metical' },
  { key: 'NAD', value: 'NAD', label: 'NAD - Namibian dollar' },
  { key: 'NGN', value: 'NGN', label: 'NGN - Nigerian naira' },
  { key: 'NIO', value: 'NIO', label: 'NIO - Nicaraguan córdoba' },
  { key: 'NOK', value: 'NOK', label: 'NOK - Norwegian krone' },
  { key: 'NPR', value: 'NPR', label: 'NPR - Nepalese rupee' },
  { key: 'NZD', value: 'NZD', label: 'NZD - New Zealand dollar' },
  { key: 'OMR', value: 'OMR', label: 'OMR - Omani rial' },
  { key: 'PAB', value: 'PAB', label: 'PAB - Panamanian balboa' },
  { key: 'PEN', value: 'PEN', label: 'PEN - Peruvian sol' },
  { key: 'PGK', value: 'PGK', label: 'PGK - Papua New Guinean kina' },
  { key: 'PHP', value: 'PHP', label: 'PHP - Philippine peso' },
  { key: 'PKR', value: 'PKR', label: 'PKR - Pakistani rupee' },
  { key: 'PLN', value: 'PLN', label: 'PLN - Polish złoty' },
  { key: 'PYG', value: 'PYG', label: 'PYG - Paraguayan guaraní' },
  { key: 'QAR', value: 'QAR', label: 'QAR - Qatari riyal' },
  { key: 'RON', value: 'RON', label: 'RON - Romanian leu' },
  { key: 'RSD', value: 'RSD', label: 'RSD - Serbian dinar' },
  { key: 'RUB', value: 'RUB', label: 'RUB - Russian ruble' },
  { key: 'RWF', value: 'RWF', label: 'RWF - Rwandan franc' },
  { key: 'SAR', value: 'SAR', label: 'SAR - Saudi riyal' },
  { key: 'SBD', value: 'SBD', label: 'SBD - Solomon Islands dollar' },
  { key: 'SCR', value: 'SCR', label: 'SCR - Seychellois rupee' },
  { key: 'SDG', value: 'SDG', label: 'SDG - Sudanese pound' },
  { key: 'SEK', value: 'SEK', label: 'SEK - Swedish krona' },
  { key: 'SGD', value: 'SGD', label: 'SGD - Singapore dollar' },
  { key: 'SHP', value: 'SHP', label: 'SHP - Saint Helena pound' },
  { key: 'SLL', value: 'SLL', label: 'SLL - Sierra Leonean leone' },
  { key: 'SOS', value: 'SOS', label: 'SOS - Somali shilling' },
  { key: 'SRD', value: 'SRD', label: 'SRD - Surinamese dollar' },
  { key: 'SSP', value: 'SSP', label: 'SSP - South Sudanese pound' },
  { key: 'STN', value: 'STN', label: 'STN - São Tomé and Príncipe dobra' },
  { key: 'SVC', value: 'SVC', label: 'SVC - Salvadoran colón' },
  { key: 'SYP', value: 'SYP', label: 'SYP - Syrian pound' },
  { key: 'SZL', value: 'SZL', label: 'SZL - Swazi lilangeni' },
  { key: 'THB', value: 'THB', label: 'THB - Thai baht' },
  { key: 'TJS', value: 'TJS', label: 'TJS - Tajikistani somoni' },
  { key: 'TMT', value: 'TMT', label: 'TMT - Turkmenistan manat' },
  { key: 'TND', value: 'TND', label: 'TND - Tunisian dinar' },
  { key: 'TOP', value: 'TOP', label: `TOP - Tongan pa'anga` },
  { key: 'TRY', value: 'TRY', label: 'TRY - Turkish lira' },
  { key: 'TTD', value: 'TTD', label: 'TTD - Trinidad and Tobago dollar' },
  { key: 'TWD', value: 'TWD', label: 'TWD - New Taiwan dollar' },
  { key: 'TZS', value: 'TZS', label: 'TZS - Tanzanian shilling' },
  { key: 'UAH', value: 'UAH', label: 'UAH - Ukrainian hryvnia' },
  { key: 'UGX', value: 'UGX', label: 'UGX - Ugandan shilling' },
  { key: 'USD', value: 'USD', label: 'USD - United States dollar' },
  { key: 'UYU', value: 'UYU', label: 'UYU - Uruguayan peso' },
  { key: 'UZS', value: 'UZS', label: 'UZS - Uzbekistan som' },
  { key: 'VES', value: 'VES', label: 'VES - Venezuelan bolívar soberano' },
  { key: 'VND', value: 'VND', label: 'VND - Vietnamese đồng' },
  { key: 'VUV', value: 'VUV', label: 'VUV - Vanuatu vatu' },
  { key: 'WST', value: 'WST', label: 'WST - Samoan tālā' },
  { key: 'XAF', value: 'XAF', label: 'XAF - Central African CFA franc' },
  { key: 'XCD', value: 'XCD', label: 'XCD - East Caribbean dollar' },
  { key: 'XOF', value: 'XOF', label: 'XOF - West African CFA franc' },
  { key: 'XPF', value: 'XPF', label: 'XPF - CFP franc (French Pacific franc)' },
  { key: 'YER', value: 'YER', label: 'YER - Yemeni rial' },
  { key: 'ZAR', value: 'ZAR', label: 'ZAR - South African rand' },
  { key: 'ZMW', value: 'ZMW', label: 'ZMW - Zambian kwacha' },
  { key: 'ZWL', value: 'ZWL', label: 'ZWL - Zimbabwean dollar' }
];

