export const PARCEL_BOX_TYPES = [
  {
    id: 1,
    box_type_name: 'HARD BOX - BLACK XSOS (DEMONSTRATION)',
    depth: 80,
    width: 60,
    height: 50,
    dimension_unit: 'cm',
    parcel_weight: 16.0,
    weight_unit: 'kg',
    remark: null,
  },
  {
    id: 2,
    box_type_name: 'HARD BOX - BLACK CSOS (DEMONSTRATION)',
    depth: 70,
    width: 65,
    height: 25,
    dimension_unit: 'cm',
    parcel_weight: 12.0,
    weight_unit: 'kg',
    remark: null,
  },
  {
    id: 3,
    box_type_name: 'HARD BOX - BLACK MMU (DEMONSTRATION)',
    depth: 65,
    width: 50,
    height: 40,
    dimension_unit: 'cm',
    parcel_weight: 13.5,
    weight_unit: 'kg',
    remark: null,
  },
  {
    id: 4,
    box_type_name: 'HARD BOX - GREEN XSOS (DEMONSTRATION)',
    depth: 65,
    width: 62,
    height: 45,
    dimension_unit: 'cm',
    parcel_weight: 15.0,
    weight_unit: 'kg',
    remark: '*Return DEMO from Telehouse, Germany',
  },
  {
    id: 5,
    box_type_name: 'HARD BOX - GREEN IT & EQUIPMENT',
    depth: 78,
    width: 60,
    height: 52,
    dimension_unit: 'cm',
    parcel_weight: 15.0,
    weight_unit: 'kg',
    remark: '*For Event in Malaysia',
  },
  {
    id: 6,
    box_type_name: 'PALLET (With cardboard box) XSOS (For Sales)',
    depth: 68,
    width: 60,
    height: 62,
    dimension_unit: 'cm',
    parcel_weight: 7.0,
    weight_unit: 'kg',
    remark: null,
  },
  {
    id: 7,
    box_type_name: 'WOODEN BOX (Old version) CHASSIS',
    depth: 55,
    width: 55,
    height: 50,
    dimension_unit: 'cm',
    parcel_weight: 14.0,
    weight_unit: 'kg',
    remark: null,
  },
  {
    id: 8,
    box_type_name: 'WOODEN BOX (New version) CHASSIS',
    depth: 57,
    width: 56,
    height: 51,
    dimension_unit: 'cm',
    parcel_weight: 15.0,
    weight_unit: 'kg',
    remark: null,
  },
  {
    id: 9,
    box_type_name: 'CARDBOARD BOX PARTS AND OTHER',
    depth: 0,
    width: 0,
    height: 0,
    dimension_unit: 'cm',
    parcel_weight: 0.0,
    weight_unit: 'kg',
    remark: null,
  }
];
