export { default as BasicInformation } from './BasicInformation'
export { default as AddressSelector } from './AddressSelector'
export { default as PickupInformation } from './PickupInformation'
export { default as InsuranceInformation } from './InsuranceInformation'
export { default as ParcelsSection } from './ParcelsSection'
export { default as ParcelItems } from './ParcelItems'
export { default as RatesSection } from './RatesSection'