export const ISO_2_COUNTRIES = [
  { key: "AF", value: "AF - Afghanistan" },
  { key: "AL", value: "AL - Albania" },
  { key: "DZ", value: "DZ - Algeria" },
  { key: "AD", value: "AD - Andorra" },
  { key: "AO", value: "AO - Angola" },
  { key: "AG", value: "AG - Antigua and Barbuda" },
  { key: "AR", value: "AR - Argentina" },
  { key: "AM", value: "AM - Armenia" },
  { key: "AU", value: "AU - Australia" },
  { key: "AT", value: "AT - Austria" },
  { key: "AZ", value: "AZ - Azerbaijan" },
  { key: "BS", value: "BS - Bahamas" },
  { key: "BH", value: "BH - Bahrain" },
  { key: "BD", value: "BD - Bangladesh" },
  { key: "BB", value: "BB - Barbados" },
  { key: "BY", value: "BY - Belarus" },
  { key: "BE", value: "BE - Belgium" },
  { key: "BZ", value: "BZ - Belize" },
  { key: "BJ", value: "BJ - Benin" },
  { key: "BT", value: "BT - Bhutan" },
  { key: "BO", value: "BO - Bolivia" },
  { key: "BA", value: "BA - Bosnia and Herzegovina" },
  { key: "BW", value: "BW - Botswana" },
  { key: "BR", value: "BR - Brazil" },
  { key: "BN", value: "BN - Brunei Darussalam" },
  { key: "BG", value: "BG - Bulgaria" },
  { key: "BF", value: "BF - Burkina Faso" },
  { key: "BI", value: "BI - Burundi" },
  { key: "KH", value: "KH - Cambodia" },
  { key: "CM", value: "CM - Cameroon" },
  { key: "CA", value: "CA - Canada" },
  { key: "CV", value: "CV - Cabo Verde" },
  { key: "CF", value: "CF - Central African Republic" },
  { key: "TD", value: "TD - Chad" },
  { key: "CL", value: "CL - Chile" },
  { key: "CN", value: "CN - China" },
  { key: "CO", value: "CO - Colombia" },
  { key: "KM", value: "KM - Comoros" },
  { key: "CG", value: "CG - Congo" },
  { key: "CD", value: "CD - Congo, Democratic Republic of the" },
  { key: "CR", value: "CR - Costa Rica" },
  { key: "CI", value: "CI - Côte d'Ivoire" },
  { key: "HR", value: "HR - Croatia" },
  { key: "CU", value: "CU - Cuba" },
  { key: "CY", value: "CY - Cyprus" },
  { key: "CZ", value: "CZ - Czechia" },
  { key: "DK", value: "DK - Denmark" },
  { key: "DJ", value: "DJ - Djibouti" },
  { key: "DM", value: "DM - Dominica" },
  { key: "DO", value: "DO - Dominican Republic" },
  { key: "EC", value: "EC - Ecuador" },
  { key: "EG", value: "EG - Egypt" },
  { key: "SV", value: "SV - El Salvador" },
  { key: "GQ", value: "GQ - Equatorial Guinea" },
  { key: "ER", value: "ER - Eritrea" },
  { key: "EE", value: "EE - Estonia" },
  { key: "SZ", value: "SZ - Eswatini" },
  { key: "ET", value: "ET - Ethiopia" },
  { key: "FJ", value: "FJ - Fiji" },
  { key: "FI", value: "FI - Finland" },
  { key: "FR", value: "FR - France" },
  { key: "GA", value: "GA - Gabon" },
  { key: "GM", value: "GM - Gambia" },
  { key: "GE", value: "GE - Georgia" },
  { key: "DE", value: "DE - Germany" },
  { key: "GH", value: "GH - Ghana" },
  { key: "GR", value: "GR - Greece" },
  { key: "GD", value: "GD - Grenada" },
  { key: "GT", value: "GT - Guatemala" },
  { key: "GN", value: "GN - Guinea" },
  { key: "GW", value: "GW - Guinea-Bissau" },
  { key: "GY", value: "GY - Guyana" },
  { key: "HT", value: "HT - Haiti" },
  { key: "HN", value: "HN - Honduras" },
  { key: "HK", value: "HK - Hong Kong" },
  { key: "HU", value: "HU - Hungary" },
  { key: "IS", value: "IS - Iceland" },
  { key: "IN", value: "IN - India" },
  { key: "ID", value: "ID - Indonesia" },
  { key: "IR", value: "IR - Iran" },
  { key: "IQ", value: "IQ - Iraq" },
  { key: "IE", value: "IE - Ireland" },
  { key: "IL", value: "IL - Israel" },
  { key: "IT", value: "IT - Italy" },
  { key: "JM", value: "JM - Jamaica" },
  { key: "JP", value: "JP - Japan" },
  { key: "JO", value: "JO - Jordan" },
  { key: "KZ", value: "KZ - Kazakhstan" },
  { key: "KE", value: "KE - Kenya" },
  { key: "KI", value: "KI - Kiribati" },
  { key: "KP", value: "KP - Korea, Democratic People's Republic of" },
  { key: "KR", value: "KR - Korea, Republic of" },
  { key: "KW", value: "KW - Kuwait" },
  { key: "KG", value: "KG - Kyrgyzstan" },
  { key: "LA", value: "LA - Lao People's Democratic Republic" },
  { key: "LV", value: "LV - Latvia" },
  { key: "LB", value: "LB - Lebanon" },
  { key: "LS", value: "LS - Lesotho" },
  { key: "LR", value: "LR - Liberia" },
  { key: "LY", value: "LY - Libya" },
  { key: "LI", value: "LI - Liechtenstein" },
  { key: "LT", value: "LT - Lithuania" },
  { key: "LU", value: "LU - Luxembourg" },
  { key: "MG", value: "MG - Madagascar" },
  { key: "MW", value: "MW - Malawi" },
  { key: "MY", value: "MY - Malaysia" },
  { key: "MV", value: "MV - Maldives" },
  { key: "ML", value: "ML - Mali" },
  { key: "MT", value: "MT - Malta" },
  { key: "MH", value: "MH - Marshall Islands" },
  { key: "MR", value: "MR - Mauritania" },
  { key: "MU", value: "MU - Mauritius" },
  { key: "MX", value: "MX - Mexico" },
  { key: "FM", value: "FM - Micronesia" },
  { key: "MD", value: "MD - Moldova" },
  { key: "MC", value: "MC - Monaco" },
  { key: "MN", value: "MN - Mongolia" },
  { key: "ME", value: "ME - Montenegro" },
  { key: "MA", value: "MA - Morocco" },
  { key: "MZ", value: "MZ - Mozambique" },
  { key: "MM", value: "MM - Myanmar" },
  { key: "NA", value: "NA - Namibia" },
  { key: "NR", value: "NR - Nauru" },
  { key: "NP", value: "NP - Nepal" },
  { key: "NL", value: "NL - Netherlands" },
  { key: "NZ", value: "NZ - New Zealand" },
  { key: "NI", value: "NI - Nicaragua" },
  { key: "NE", value: "NE - Niger" },
  { key: "NG", value: "NG - Nigeria" },
  { key: "MK", value: "MK - North Macedonia" },
  { key: "NO", value: "NO - Norway" },
  { key: "OM", value: "OM - Oman" },
  { key: "PK", value: "PK - Pakistan" },
  { key: "PW", value: "PW - Palau" },
  { key: "PS", value: "PS - Palestine, State of" },
  { key: "PA", value: "PA - Panama" },
  { key: "PG", value: "PG - Papua New Guinea" },
  { key: "PY", value: "PY - Paraguay" },
  { key: "PE", value: "PE - Peru" },
  { key: "PH", value: "PH - Philippines" },
  { key: "PL", value: "PL - Poland" },
  { key: "PT", value: "PT - Portugal" },
  { key: "QA", value: "QA - Qatar" },
  { key: "RO", value: "RO - Romania" },
  { key: "RU", value: "RU - Russian Federation" },
  { key: "RW", value: "RW - Rwanda" },
  { key: "KN", value: "KN - Saint Kitts and Nevis" },
  { key: "LC", value: "LC - Saint Lucia" },
  { key: "VC", value: "VC - Saint Vincent and the Grenadines" },
  { key: "WS", value: "WS - Samoa" },
  { key: "SM", value: "SM - San Marino" },
  { key: "ST", value: "ST - Sao Tome and Principe" },
  { key: "SA", value: "SA - Saudi Arabia" },
  { key: "SN", value: "SN - Senegal" },
  { key: "RS", value: "RS - Serbia" },
  { key: "SC", value: "SC - Seychelles" },
  { key: "SL", value: "SL - Sierra Leone" },
  { key: "SG", value: "SG - Singapore" },
  { key: "SK", value: "SK - Slovakia" },
  { key: "SI", value: "SI - Slovenia" },
  { key: "SB", value: "SB - Solomon Islands" },
  { key: "SO", value: "SO - Somalia" },
  { key: "ZA", value: "ZA - South Africa" },
  { key: "SS", value: "SS - South Sudan" },
  { key: "ES", value: "ES - Spain" },
  { key: "LK", value: "LK - Sri Lanka" },
  { key: "SD", value: "SD - Sudan" },
  { key: "SR", value: "SR - Suriname" },
  { key: "SE", value: "SE - Sweden" },
  { key: "CH", value: "CH - Switzerland" },
  { key: "SY", value: "SY - Syrian Arab Republic" },
  { key: "TW", value: "TW - Taiwan, Province of China" },
  { key: "TJ", value: "TJ - Tajikistan" },
  { key: "TZ", value: "TZ - Tanzania" },
  { key: "TH", value: "TH - Thailand" },
  { key: "TL", value: "TL - Timor-Leste" },
  { key: "TG", value: "TG - Togo" },
  { key: "TO", value: "TO - Tonga" },
  { key: "TT", value: "TT - Trinidad and Tobago" },
  { key: "TN", value: "TN - Tunisia" },
  { key: "TR", value: "TR - Turkey" },
  { key: "TM", value: "TM - Turkmenistan" },
  { key: "TV", value: "TV - Tuvalu" },
  { key: "UG", value: "UG - Uganda" },
  { key: "UA", value: "UA - Ukraine" },
  { key: "AE", value: "AE - United Arab Emirates" },
  { key: "GB", value: "GB - United Kingdom" },
  { key: "US", value: "US - United States of America" },
  { key: "UY", value: "UY - Uruguay" },
  { key: "UZ", value: "UZ - Uzbekistan" },
  { key: "VU", value: "VU - Vanuatu" },
  { key: "VE", value: "VE - Venezuela" },
  { key: "VN", value: "VN - Viet Nam" },
  { key: "YE", value: "YE - Yemen" },
  { key: "ZM", value: "ZM - Zambia" },
  { key: "ZW", value: "ZW - Zimbabwe" }
];
