export const ISO_3_COUNTRIES = [
  { key: "AFG", value: "AFG - Afghanistan" },
  { key: "ALB", value: "ALB - Albania" },
  { key: "DZA", value: "DZA - Algeria" },
  { key: "AND", value: "AND - Andorra" },
  { key: "AGO", value: "AGO - Angola" },
  { key: "ATG", value: "ATG - Antigua and Barbuda" },
  { key: "ARG", value: "ARG - Argentina" },
  { key: "ARM", value: "ARM - Armenia" },
  { key: "AUS", value: "AUS - Australia" },
  { key: "AUT", value: "AUT - Austria" },
  { key: "AZE", value: "AZE - Azerbaijan" },
  { key: "BHS", value: "BHS - Bahamas" },
  { key: "BHR", value: "BHR - Bahrain" },
  { key: "BGD", value: "BGD - Bangladesh" },
  { key: "BRB", value: "BRB - Barbados" },
  { key: "BLR", value: "BLR - Belarus" },
  { key: "BEL", value: "BEL - Belgium" },
  { key: "BLZ", value: "BLZ - Belize" },
  { key: "BEN", value: "BEN - Benin" },
  { key: "BTN", value: "BTN - Bhutan" },
  { key: "BOL", value: "BOL - Bolivia" },
  { key: "BIH", value: "BIH - Bosnia and Herzegovina" },
  { key: "BWA", value: "BWA - Botswana" },
  { key: "BRA", value: "BRA - Brazil" },
  { key: "BRN", value: "BRN - Brunei Darussalam" },
  { key: "BGR", value: "BGR - Bulgaria" },
  { key: "BFA", value: "BFA - Burkina Faso" },
  { key: "BDI", value: "BDI - Burundi" },
  { key: "KHM", value: "KHM - Cambodia" },
  { key: "CMR", value: "CMR - Cameroon" },
  { key: "CAN", value: "CAN - Canada" },
  { key: "CPV", value: "CPV - Cabo Verde" },
  { key: "CAF", value: "CAF - Central African Republic" },
  { key: "TCD", value: "TCD - Chad" },
  { key: "CHL", value: "CHL - Chile" },
  { key: "CHN", value: "CHN - China" },
  { key: "COL", value: "COL - Colombia" },
  { key: "COM", value: "COM - Comoros" },
  { key: "COG", value: "COG - Congo" },
  { key: "COD", value: "COD - Congo, Democratic Republic of the" },
  { key: "CRI", value: "CRI - Costa Rica" },
  { key: "CIV", value: "CIV - Côte d'Ivoire" },
  { key: "HRV", value: "HRV - Croatia" },
  { key: "CUB", value: "CUB - Cuba" },
  { key: "CYP", value: "CYP - Cyprus" },
  { key: "CZE", value: "CZE - Czechia" },
  { key: "DNK", value: "DNK - Denmark" },
  { key: "DJI", value: "DJI - Djibouti" },
  { key: "DMA", value: "DMA - Dominica" },
  { key: "DOM", value: "DOM - Dominican Republic" },
  { key: "ECU", value: "ECU - Ecuador" },
  { key: "EGY", value: "EGY - Egypt" },
  { key: "SLV", value: "SLV - El Salvador" },
  { key: "GNQ", value: "GNQ - Equatorial Guinea" },
  { key: "ERI", value: "ERI - Eritrea" },
  { key: "EST", value: "EST - Estonia" },
  { key: "SWZ", value: "SWZ - Eswatini" },
  { key: "ETH", value: "ETH - Ethiopia" },
  { key: "FJI", value: "FJI - Fiji" },
  { key: "FIN", value: "FIN - Finland" },
  { key: "FRA", value: "FRA - France" },
  { key: "GAB", value: "GAB - Gabon" },
  { key: "GMB", value: "GMB - Gambia" },
  { key: "GEO", value: "GEO - Georgia" },
  { key: "DEU", value: "DEU - Germany" },
  { key: "GHA", value: "GHA - Ghana" },
  { key: "GRC", value: "GRC - Greece" },
  { key: "GRD", value: "GRD - Grenada" },
  { key: "GTM", value: "GTM - Guatemala" },
  { key: "GIN", value: "GIN - Guinea" },
  { key: "GNB", value: "GNB - Guinea-Bissau" },
  { key: "GUY", value: "GUY - Guyana" },
  { key: "HTI", value: "HTI - Haiti" },
  { key: "HND", value: "HND - Honduras" },
  { key: "HKG", value: "HKG - Hong Kong" },
  { key: "HUN", value: "HUN - Hungary" },
  { key: "ISL", value: "ISL - Iceland" },
  { key: "IND", value: "IND - India" },
  { key: "IDN", value: "IDN - Indonesia" },
  { key: "IRN", value: "IRN - Iran" },
  { key: "IRQ", value: "IRQ - Iraq" },
  { key: "IRL", value: "IRL - Ireland" },
  { key: "ISR", value: "ISR - Israel" },
  { key: "ITA", value: "ITA - Italy" },
  { key: "JAM", value: "JAM - Jamaica" },
  { key: "JPN", value: "JPN - Japan" },
  { key: "JOR", value: "JOR - Jordan" },
  { key: "KAZ", value: "KAZ - Kazakhstan" },
  { key: "KEN", value: "KEN - Kenya" },
  { key: "KIR", value: "KIR - Kiribati" },
  { key: "PRK", value: "PRK - Korea, Democratic People's Republic of" },
  { key: "KOR", value: "KOR - Korea, Republic of" },
  { key: "KWT", value: "KWT - Kuwait" },
  { key: "KGZ", value: "KGZ - Kyrgyzstan" },
  { key: "LAO", value: "LAO - Lao People's Democratic Republic" },
  { key: "LVA", value: "LVA - Latvia" },
  { key: "LBN", value: "LBN - Lebanon" },
  { key: "LSO", value: "LSO - Lesotho" },
  { key: "LBR", value: "LBR - Liberia" },
  { key: "LBY", value: "LBY - Libya" },
  { key: "LIE", value: "LIE - Liechtenstein" },
  { key: "LTU", value: "LTU - Lithuania" },
  { key: "LUX", value: "LUX - Luxembourg" },
  { key: "MDG", value: "MDG - Madagascar" },
  { key: "MWI", value: "MWI - Malawi" },
  { key: "MYS", value: "MYS - Malaysia" },
  { key: "MDV", value: "MDV - Maldives" },
  { key: "MLI", value: "MLI - Mali" },
  { key: "MLT", value: "MLT - Malta" },
  { key: "MHL", value: "MHL - Marshall Islands" },
  { key: "MRT", value: "MRT - Mauritania" },
  { key: "MUS", value: "MUS - Mauritius" },
  { key: "MEX", value: "MEX - Mexico" },
  { key: "FSM", value: "FSM - Micronesia" },
  { key: "MDA", value: "MDA - Moldova" },
  { key: "MCO", value: "MCO - Monaco" },
  { key: "MNG", value: "MNG - Mongolia" },
  { key: "MNE", value: "MNE - Montenegro" },
  { key: "MAR", value: "MAR - Morocco" },
  { key: "MOZ", value: "MOZ - Mozambique" },
  { key: "MMR", value: "MMR - Myanmar" },
  { key: "NAM", value: "NAM - Namibia" },
  { key: "NRU", value: "NRU - Nauru" },
  { key: "NPL", value: "NPL - Nepal" },
  { key: "NLD", value: "NLD - Netherlands" },
  { key: "NZL", value: "NZL - New Zealand" },
  { key: "NIC", value: "NIC - Nicaragua" },
  { key: "NER", value: "NER - Niger" },
  { key: "NGA", value: "NGA - Nigeria" },
  { key: "MKD", value: "MKD - North Macedonia" },
  { key: "NOR", value: "NOR - Norway" },
  { key: "OMN", value: "OMN - Oman" },
  { key: "PAK", value: "PAK - Pakistan" },
  { key: "PLW", value: "PLW - Palau" },
  { key: "PSE", value: "PSE - Palestine, State of" },
  { key: "PAN", value: "PAN - Panama" },
  { key: "PNG", value: "PNG - Papua New Guinea" },
  { key: "PRY", value: "PRY - Paraguay" },
  { key: "PER", value: "PER - Peru" },
  { key: "PHL", value: "PHL - Philippines" },
  { key: "POL", value: "POL - Poland" },
  { key: "PRT", value: "PRT - Portugal" },
  { key: "QAT", value: "QAT - Qatar" },
  { key: "ROU", value: "ROU - Romania" },
  { key: "RUS", value: "RUS - Russian Federation" },
  { key: "RWA", value: "RWA - Rwanda" },
  { key: "KNA", value: "KNA - Saint Kitts and Nevis" },
  { key: "LCA", value: "LCA - Saint Lucia" },
  { key: "VCT", value: "VCT - Saint Vincent and the Grenadines" },
  { key: "WSM", value: "WSM - Samoa" },
  { key: "SMR", value: "SMR - San Marino" },
  { key: "STP", value: "STP - Sao Tome and Principe" },
  { key: "SAU", value: "SAU - Saudi Arabia" },
  { key: "SEN", value: "SEN - Senegal" },
  { key: "SRB", value: "SRB - Serbia" },
  { key: "SYC", value: "SYC - Seychelles" },
  { key: "SLE", value: "SLE - Sierra Leone" },
  { key: "SGP", value: "SGP - Singapore" },
  { key: "SVK", value: "SVK - Slovakia" },
  { key: "SVN", value: "SVN - Slovenia" },
  { key: "SLB", value: "SLB - Solomon Islands" },
  { key: "SOM", value: "SOM - Somalia" },
  { key: "ZAF", value: "ZAF - South Africa" },
  { key: "SSD", value: "SSD - South Sudan" },
  { key: "ESP", value: "ESP - Spain" },
  { key: "LKA", value: "LKA - Sri Lanka" },
  { key: "SDN", value: "SDN - Sudan" },
  { key: "SUR", value: "SUR - Suriname" },
  { key: "SWE", value: "SWE - Sweden" },
  { key: "CHE", value: "CHE - Switzerland" },
  { key: "SYR", value: "SYR - Syrian Arab Republic" },
  { key: "TWN", value: "TWN - Taiwan, Province of China" },
  { key: "TJK", value: "TJK - Tajikistan" },
  { key: "TZA", value: "TZA - Tanzania" },
  { key: "THA", value: "THA - Thailand" },
  { key: "TLS", value: "TLS - Timor-Leste" },
  { key: "TGO", value: "TGO - Togo" },
  { key: "TON", value: "TON - Tonga" },
  { key: "TTO", value: "TTO - Trinidad and Tobago" },
  { key: "TUN", value: "TUN - Tunisia" },
  { key: "TUR", value: "TUR - Turkey" },
  { key: "TKM", value: "TKM - Turkmenistan" },
  { key: "TUV", value: "TUV - Tuvalu" },
  { key: "UGA", value: "UGA - Uganda" },
  { key: "UKR", value: "UKR - Ukraine" },
  { key: "ARE", value: "ARE - United Arab Emirates" },
  { key: "GBR", value: "GBR - United Kingdom" },
  { key: "USA", value: "USA - United States of America" },
  { key: "URY", value: "URY - Uruguay" },
  { key: "UZB", value: "UZB - Uzbekistan" },
  { key: "VUT", value: "VUT - Vanuatu" },
  { key: "VEN", value: "VEN - Venezuela" },
  { key: "VNM", value: "VNM - Viet Nam" },
  { key: "YEM", value: "YEM - Yemen" },
  { key: "ZMB", value: "ZMB - Zambia" },
  { key: "ZWE", value: "ZWE - Zimbabwe" }
];
