export const PARCEL_BOX_TYPES = [
  {
    id: 1,
    type:'HARD BOX - BLACK',
    box_type_name: 'HARD BOX - BLACK XSOS-1',
    depth: 80,
    width: 60,
    height: 50,
    dimension_unit: 'cm',
    parcel_weight: 16.0,
    weight_unit: 'kg',
    remark: null,
  },
  {
    id: 2,
    type:'HARD BOX - BLACK',
    box_type_name: 'HARD BOX - BLACK XSOS-2',
    depth: 90,
    width: 60,
    height: 50,
    dimension_unit: 'cm',
    parcel_weight: 20.2,
    weight_unit: 'kg',
    remark: null,
  },
  {
    id: 3,
    type:'HARD BOX - BLACK',
    box_type_name: 'HARD BOX - BLACK CSOS',
    depth: 70,
    width: 65,
    height: 25,
    dimension_unit: 'cm',
    parcel_weight: 12.0,
    weight_unit: 'kg',
    remark: null,
  },
  {
    id: 4,
    type:'HARD BOX - BLACK',
    box_type_name: 'HARD BOX - BLACK MMU',
    depth: 65,
    width: 50,
    height: 40,
    dimension_unit: 'cm',
    parcel_weight: 13.5,
    weight_unit: 'kg',
    remark: null,
  },
  {
    id: 5,
    type:'HARD BOX - GREEN',
    box_type_name: 'HARD BOX - GREEN Ver-1',
    depth: 65,
    width: 62,
    height: 45,
    dimension_unit: 'cm',
    parcel_weight: 15.0,
    weight_unit: 'kg',
    remark: null,
  },
  {
    id: 6,
    type:'HARD BOX - GREEN',
    box_type_name: 'HARD BOX - GREEN Ver-2',
    depth: 78,
    width: 60,
    height: 52,
    dimension_unit: 'cm',
    parcel_weight: 15.0,
    weight_unit: 'kg',
    remark: null,
  },
  {
    id: 7,
    type:'PALLET (With cardboard box)',
    box_type_name: 'PALLET (With cardboard box) XSOS',
    depth: 68,
    width: 60,
    height: 62,
    dimension_unit: 'cm',
    parcel_weight: 7.0,
    weight_unit: 'kg',
    remark: null,
  },
  {
    id: 8,
    type:'WOODEN BOX',
    box_type_name: 'WOODEN BOX CHASSIS-1',
    depth: 55,
    width: 55,
    height: 50,
    dimension_unit: 'cm',
    parcel_weight: 14.0,
    weight_unit: 'kg',
    remark: null,
  },
  {
    id: 9,
    type:'WOODEN BOX',
    box_type_name: 'WOODEN BOX CHASSIS-2',
    depth: 57,
    width: 56,
    height: 51,
    dimension_unit: 'cm',
    parcel_weight: 15.0,
    weight_unit: 'kg',
    remark: null,
  },
  {
    id: 10,
    type:'CARDBOARD BOX',
    box_type_name: 'CARDBOARD BOX',
    depth: 0,
    width: 0,
    height: 0,
    dimension_unit: 'cm',
    parcel_weight: 0.0,
    weight_unit: 'kg',
    remark: '(Fill by requester)',
  }
];
