// All world timezones organized by region
export const TIMEZONES = [
  // UTC
  { key: 'UTC', label: 'UTC (Coordinated Universal Time) UTC+0', value: 'UTC', offset: 0 },

  // Pacific/Americas - West to East (UTC-12 to UTC-3)
  { key: 'Pacific/Midway', label: 'SST (Samoa) UTC-11', value: 'Pacific/Midway', offset: -11 },
  { key: 'Pacific/Honolulu', label: 'HST (Hawaii) UTC-10', value: 'Pacific/Honolulu', offset: -10 },
  { key: 'America/Anchorage', label: 'AKST/AKDT (Alaska) UTC-9/-8', value: 'America/Anchorage', offset: -9 },
  { key: 'America/Los_Angeles', label: 'PST/PDT (Pacific - US/Canada) UTC-8/-7', value: 'America/Los_Angeles', offset: -8 },
  { key: 'America/Tijuana', label: 'PST/PDT (Tijuana) UTC-8/-7', value: 'America/Tijuana', offset: -8 },
  { key: 'America/Phoenix', label: 'MST (Arizona) UTC-7', value: 'America/Phoenix', offset: -7 },
  { key: 'America/Denver', label: 'MST/MDT (Mountain - US/Canada) UTC-7/-6', value: 'America/Denver', offset: -7 },
  { key: 'America/Chihuahua', label: 'MST/MDT (Chihuahua) UTC-7/-6', value: 'America/Chihuahua', offset: -7 },
  { key: 'America/Chicago', label: 'CST/CDT (Central - US/Canada) UTC-6/-5', value: 'America/Chicago', offset: -6 },
  { key: 'America/Mexico_City', label: 'CST/CDT (Mexico City) UTC-6/-5', value: 'America/Mexico_City', offset: -6 },
  { key: 'America/Guatemala', label: 'CST (Central America) UTC-6', value: 'America/Guatemala', offset: -6 },
  { key: 'America/New_York', label: 'EST/EDT (Eastern - US/Canada) UTC-5/-4', value: 'America/New_York', offset: -5 },
  { key: 'America/Bogota', label: 'COT (Colombia) UTC-5', value: 'America/Bogota', offset: -5 },
  { key: 'America/Lima', label: 'PET (Peru) UTC-5', value: 'America/Lima', offset: -5 },
  { key: 'America/Caracas', label: 'VET (Venezuela) UTC-4', value: 'America/Caracas', offset: -4 },
  { key: 'America/Halifax', label: 'AST/ADT (Atlantic Time) UTC-4/-3', value: 'America/Halifax', offset: -4 },
  { key: 'America/La_Paz', label: 'BOT (Bolivia) UTC-4', value: 'America/La_Paz', offset: -4 },
  { key: 'America/Santiago', label: 'CLT/CLST (Chile) UTC-4/-3', value: 'America/Santiago', offset: -4 },
  { key: 'America/St_Johns', label: 'NST/NDT (Newfoundland) UTC-3:30/-2:30', value: 'America/St_Johns', offset: -3.5 },
  { key: 'America/Sao_Paulo', label: 'BRT (Brazil - São Paulo) UTC-3', value: 'America/Sao_Paulo', offset: -3 },
  { key: 'America/Argentina/Buenos_Aires', label: 'ART (Argentina) UTC-3', value: 'America/Argentina/Buenos_Aires', offset: -3 },
  { key: 'America/Godthab', label: 'WGT (Greenland) UTC-3', value: 'America/Godthab', offset: -3 },
  { key: 'America/Montevideo', label: 'UYT (Uruguay) UTC-3', value: 'America/Montevideo', offset: -3 },

  // Europe & Africa (UTC-1 to UTC+3)
  { key: 'Atlantic/Azores', label: 'AZOT/AZOST (Azores) UTC-1/+0', value: 'Atlantic/Azores', offset: -1 },
  { key: 'Atlantic/Cape_Verde', label: 'CVT (Cape Verde) UTC-1', value: 'Atlantic/Cape_Verde', offset: -1 },
  { key: 'Europe/London', label: 'GMT/BST (London, UK) UTC+0/+1', value: 'Europe/London', offset: 0 },
  { key: 'Europe/Dublin', label: 'GMT/IST (Dublin, Ireland) UTC+0/+1', value: 'Europe/Dublin', offset: 0 },
  { key: 'Europe/Lisbon', label: 'WET/WEST (Lisbon) UTC+0/+1', value: 'Europe/Lisbon', offset: 0 },
  { key: 'Africa/Casablanca', label: 'WET (Morocco) UTC+0/+1', value: 'Africa/Casablanca', offset: 0 },
  { key: 'Europe/Paris', label: 'CET/CEST (Paris, France) UTC+1/+2', value: 'Europe/Paris', offset: 1 },
  { key: 'Europe/Berlin', label: 'CET/CEST (Berlin, Germany) UTC+1/+2', value: 'Europe/Berlin', offset: 1 },
  { key: 'Europe/Rome', label: 'CET/CEST (Rome, Italy) UTC+1/+2', value: 'Europe/Rome', offset: 1 },
  { key: 'Europe/Amsterdam', label: 'CET/CEST (Amsterdam) UTC+1/+2', value: 'Europe/Amsterdam', offset: 1 },
  { key: 'Europe/Brussels', label: 'CET/CEST (Brussels) UTC+1/+2', value: 'Europe/Brussels', offset: 1 },
  { key: 'Europe/Madrid', label: 'CET/CEST (Madrid, Spain) UTC+1/+2', value: 'Europe/Madrid', offset: 1 },
  { key: 'Africa/Lagos', label: 'WAT (West Africa) UTC+1', value: 'Africa/Lagos', offset: 1 },
  { key: 'Europe/Athens', label: 'EET/EEST (Athens, Greece) UTC+2/+3', value: 'Europe/Athens', offset: 2 },
  { key: 'Europe/Bucharest', label: 'EET/EEST (Bucharest) UTC+2/+3', value: 'Europe/Bucharest', offset: 2 },
  { key: 'Europe/Helsinki', label: 'EET/EEST (Helsinki) UTC+2/+3', value: 'Europe/Helsinki', offset: 2 },
  { key: 'Africa/Cairo', label: 'EET (Cairo, Egypt) UTC+2', value: 'Africa/Cairo', offset: 2 },
  { key: 'Africa/Johannesburg', label: 'SAST (South Africa) UTC+2', value: 'Africa/Johannesburg', offset: 2 },
  { key: 'Asia/Jerusalem', label: 'IST (Israel) UTC+2/+3', value: 'Asia/Jerusalem', offset: 2 },
  { key: 'Europe/Istanbul', label: 'TRT (Turkey) UTC+3', value: 'Europe/Istanbul', offset: 3 },
  { key: 'Europe/Moscow', label: 'MSK (Moscow, Russia) UTC+3', value: 'Europe/Moscow', offset: 3 },
  { key: 'Africa/Nairobi', label: 'EAT (East Africa) UTC+3', value: 'Africa/Nairobi', offset: 3 },
  { key: 'Asia/Baghdad', label: 'AST (Iraq) UTC+3', value: 'Asia/Baghdad', offset: 3 },
  { key: 'Asia/Kuwait', label: 'AST (Kuwait) UTC+3', value: 'Asia/Kuwait', offset: 3 },
  { key: 'Asia/Riyadh', label: 'AST (Saudi Arabia) UTC+3', value: 'Asia/Riyadh', offset: 3 },

  // Middle East & Central Asia (UTC+3:30 to UTC+6)
  { key: 'Asia/Tehran', label: 'IRST/IRDT (Iran) UTC+3:30/+4:30', value: 'Asia/Tehran', offset: 3.5 },
  { key: 'Asia/Dubai', label: 'GST (UAE, Dubai) UTC+4', value: 'Asia/Dubai', offset: 4 },
  { key: 'Asia/Muscat', label: 'GST (Oman) UTC+4', value: 'Asia/Muscat', offset: 4 },
  { key: 'Asia/Baku', label: 'AZT (Azerbaijan) UTC+4', value: 'Asia/Baku', offset: 4 },
  { key: 'Asia/Tbilisi', label: 'GET (Georgia) UTC+4', value: 'Asia/Tbilisi', offset: 4 },
  { key: 'Asia/Yerevan', label: 'AMT (Armenia) UTC+4', value: 'Asia/Yerevan', offset: 4 },
  { key: 'Asia/Kabul', label: 'AFT (Afghanistan) UTC+4:30', value: 'Asia/Kabul', offset: 4.5 },
  { key: 'Asia/Karachi', label: 'PKT (Pakistan) UTC+5', value: 'Asia/Karachi', offset: 5 },
  { key: 'Asia/Tashkent', label: 'UZT (Uzbekistan) UTC+5', value: 'Asia/Tashkent', offset: 5 },
  { key: 'Asia/Kolkata', label: 'IST (India) UTC+5:30', value: 'Asia/Kolkata', offset: 5.5 },
  { key: 'Asia/Colombo', label: 'IST (Sri Lanka) UTC+5:30', value: 'Asia/Colombo', offset: 5.5 },
  { key: 'Asia/Kathmandu', label: 'NPT (Nepal) UTC+5:45', value: 'Asia/Kathmandu', offset: 5.75 },
  { key: 'Asia/Dhaka', label: 'BST (Bangladesh) UTC+6', value: 'Asia/Dhaka', offset: 6 },
  { key: 'Asia/Almaty', label: 'ALMT (Kazakhstan) UTC+6', value: 'Asia/Almaty', offset: 6 },

  // Southeast & East Asia (UTC+6:30 to UTC+9)
  { key: 'Asia/Yangon', label: 'MMT (Myanmar) UTC+6:30', value: 'Asia/Yangon', offset: 6.5 },
  { key: 'Asia/Bangkok', label: 'ICT (Thailand) UTC+7', value: 'Asia/Bangkok', offset: 7 },
  { key: 'Asia/Ho_Chi_Minh', label: 'ICT (Vietnam) UTC+7', value: 'Asia/Ho_Chi_Minh', offset: 7 },
  { key: 'Asia/Jakarta', label: 'WIB (Western Indonesia) UTC+7', value: 'Asia/Jakarta', offset: 7 },
  { key: 'Asia/Phnom_Penh', label: 'ICT (Cambodia) UTC+7', value: 'Asia/Phnom_Penh', offset: 7 },
  { key: 'Asia/Singapore', label: 'SGT (Singapore) UTC+8', value: 'Asia/Singapore', offset: 8 },
  { key: 'Asia/Kuala_Lumpur', label: 'MYT (Malaysia) UTC+8', value: 'Asia/Kuala_Lumpur', offset: 8 },
  { key: 'Asia/Manila', label: 'PHT (Philippines) UTC+8', value: 'Asia/Manila', offset: 8 },
  { key: 'Asia/Hong_Kong', label: 'HKT (Hong Kong) UTC+8', value: 'Asia/Hong_Kong', offset: 8 },
  { key: 'Asia/Shanghai', label: 'CST (China) UTC+8', value: 'Asia/Shanghai', offset: 8 },
  { key: 'Asia/Taipei', label: 'CST (Taiwan) UTC+8', value: 'Asia/Taipei', offset: 8 },
  { key: 'Asia/Macau', label: 'CST (Macau) UTC+8', value: 'Asia/Macau', offset: 8 },
  { key: 'Asia/Ulaanbaatar', label: 'ULAT (Mongolia) UTC+8', value: 'Asia/Ulaanbaatar', offset: 8 },
  { key: 'Asia/Tokyo', label: 'JST (Japan) UTC+9', value: 'Asia/Tokyo', offset: 9 },
  { key: 'Asia/Seoul', label: 'KST (Korea) UTC+9', value: 'Asia/Seoul', offset: 9 },
  { key: 'Asia/Pyongyang', label: 'KST (North Korea) UTC+9', value: 'Asia/Pyongyang', offset: 9 },

  // Australia & Pacific (UTC+9:30 to UTC+14)
  { key: 'Australia/Darwin', label: 'ACST (Darwin) UTC+9:30', value: 'Australia/Darwin', offset: 9.5 },
  { key: 'Australia/Adelaide', label: 'ACDT/ACST (Adelaide) UTC+10:30/+9:30', value: 'Australia/Adelaide', offset: 9.5 },
  { key: 'Australia/Brisbane', label: 'AEST (Brisbane) UTC+10', value: 'Australia/Brisbane', offset: 10 },
  { key: 'Australia/Sydney', label: 'AEDT/AEST (Sydney) UTC+11/+10', value: 'Australia/Sydney', offset: 10 },
  { key: 'Australia/Melbourne', label: 'AEDT/AEST (Melbourne) UTC+11/+10', value: 'Australia/Melbourne', offset: 10 },
  { key: 'Pacific/Guam', label: 'ChST (Guam) UTC+10', value: 'Pacific/Guam', offset: 10 },
  { key: 'Pacific/Port_Moresby', label: 'PGT (Papua New Guinea) UTC+10', value: 'Pacific/Port_Moresby', offset: 10 },
  { key: 'Asia/Vladivostok', label: 'VLAT (Vladivostok) UTC+10', value: 'Asia/Vladivostok', offset: 10 },
  { key: 'Pacific/Guadalcanal', label: 'SBT (Solomon Islands) UTC+11', value: 'Pacific/Guadalcanal', offset: 11 },
  { key: 'Pacific/Fiji', label: 'FJT (Fiji) UTC+12/+13', value: 'Pacific/Fiji', offset: 12 },
  { key: 'Pacific/Auckland', label: 'NZDT/NZST (New Zealand) UTC+13/+12', value: 'Pacific/Auckland', offset: 12 },
  { key: 'Pacific/Tongatapu', label: 'TOT (Tonga) UTC+13', value: 'Pacific/Tongatapu', offset: 13 },
  { key: 'Pacific/Kiritimati', label: 'LINT (Line Islands) UTC+14', value: 'Pacific/Kiritimati', offset: 14 },
]